CREATE TABLE ATTENDEE (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    login VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL
);

CREATE TABLE RESERVATION (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    lecture_id BIGINT NOT NULL,
    attendee_id BIGINT NOT NULL
);

ALTER TABLE RESERVATION
    ADD CONSTRAINT reservation_attendee_id
    FOREIGN KEY (attendee_id) REFERENCES ATTENDEE(id)